<?php

namespace App\Http\Controllers;

use App\Baskets;
use Illuminate\Http\Request;

class BasketsController extends Controller
{
    public function index()
    {
        return view('baskets');
    }

    public static function store($request)
    {
        dd('Hello');
        return 'HELLO';
//        dd($request,$parameters);
        // Check whether the basket already exists
        // Fetch record if it does
        // Create new if it does't
        // Delete the record

//$basket = new Baskets();

//        parent::store($method, $parameters); // TODO: Change the autogenerated stub
    }
}
